import Head from "next/head";

export default function Home() {
  return (
    <div className="flex flex-col  items-center justify-center min-h-screen py-2 bg-gray-100 ')] ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  );
}
