import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  FaFacebookF,
  FaLinkedinIn,
  FaGoogle,
  FaRegEnvelope,
} from "react-icons/fa";
import { MdLockOutline } from "react-icons/md";
export default function Register() {
  return (
    <div className="flex flex-col  items-center justify-center min-h-screen bg-gray-100 ">
      <Head>
        <title>S'inscrire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="try  flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="  bg-white rounded-2xl shadow-2xl flex w-6/12 maw-w-4xl ">
          {/* -----------sign up section------------ */}
          <div className="w-full p-9">
            <div className="text-left font-bold">
              <span className="text-green-500">Organisateur</span>Mariage
            </div>
            <div className="py-10">
              <h2 className="text-3xl font-bold text-green-500 mb-2">
                Créer votre compte
              </h2>
              <div className="border-2 w-10 border-green-500 inline-block mb-2"></div>

              <p className="text-gray-400 my-3">Inscrivez vous </p>
              <div className="flex flex-col items-center ">
                <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                  <FaRegEnvelope className="text-gray-400 m-2" />
                  <input
                    type="text"
                    name="username"
                    placeholder="Nom"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                  <FaRegEnvelope className="text-gray-400 m-2" />
                  <input
                    type="text"
                    name="lastname"
                    placeholder="Prénom"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                  <FaRegEnvelope className="text-gray-400 m-2" />
                  <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                  <MdLockOutline className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="Mot de passe"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-64 p-2 flex items-center mb-3">
                  <MdLockOutline className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="comfirmPassword"
                    placeholder="Comfirm mot de passe"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>

                <a
                  href="#"
                  className="border-2 border-green-500 rounded-full text-green-500 py-2 px-12 inline-block font-semibold hover:bg-green-500 hover:text-white"
                >
                  Inscrivez
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
